version: '3'

services:
  yozhik:
    image: registry.vilunov.me/soramitsu/yozhik:latest
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      YOZHIK_WEBHOOK_ADDRESS: "0.0.0.0:8080"
      YOZHIK_GITHUB_TOKEN: ""
    volumes:
      - "./config/:/etc/yozhik/"
    ports:
      - "8080:8080"
